branches:
  only:
    - master
language: node_js
node_js:
  - "0.10"
before_script:
  - git remote set-url origin "https://${GH_TOKEN}@github.com/kewangtw/hbase-dataflow.git"
  - npm install -g bower
  - npm install -g grunt-cli
  - bower install
  - grunt
env:
  global:
    - secure: "MsCYDsQAVbml5vTOrGbuh7YilSirFsefqNpDFwdUbZW4MOacguEUEVCO4ME2m7jBVSwXxqGSNngt//p4YKDTEVM4aNrFGjtcESvHle1kDn0PyCCIjMWpoPBVhGe8EehT8QM7OOUAH8mtMaggSi0KpXm4cicq4AQjHTjp0P5EPLc="
